//------------------------------------------------------------------------
// Copyright(c) 2023 pjmw.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"plugin1.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"plugin1 VST3 (64Bit)"
#else
#define stringFileDescription	"plugin1 VST3"
#endif
#define stringCompanyName		"pjmw\0"
#define stringLegalCopyright	"Copyright(c) 2023 pjmw."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
